// BOOKS
export const GET_BOOKS_START = "GET_BOOKS_START";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAIL = "GET_BOOKS_FAIL";

export const GET_BOOK_DETAILS_START = "GET_BOOK_DETAILS_START";
export const GET_BOOK_DETAILS_SUCCESS = "GET_BOOK_DETAILS_SUCCESS";
export const GET_BOOK_DETAILS_FAIL = "GET_BOOK_DETAILS_FAIL";

export const PUT_BOOK_START = "PUT_BOOK_START";
export const PUT_BOOK_SUCCESS = "PUT_BOOK_SUCCESS";
export const PUT_BOOK_FAIL = "PUT_BOOK_FAIL";

export const DELETE_BOOK_START = "DELETE_BOOK_START";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

export const CREATE_BOOK_START = "CREATE_BOOK_START";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAIL = "CREATE_BOOK_FAIL";

export const CREATE_BOOK_RESERVATION_START = "CREATE_BOOK_RESERVATION_START";
export const CREATE_BOOK_RESERVATION_SUCCESS = "CREATE_BOOK_RESERVATION_SUCCESS";
export const CREATE_BOOK_RESERVATION_FAIL = "CREATE_BOOK_RESERVATION_FAIL";

export const GET_RESERVATIONS_START = "GET_RESERVATIONS_START";
export const GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_RESERVATIONS_FAIL = "GET_RESERVATIONS_FAIL";

// PUBLISHERS
export const GET_PUBLISHERS_START = "GET_PUBLISHERS_START";
export const GET_PUBLISHERS_SUCCESS = "GET_PUBLISHERS_SUCCESS";
export const GET_PUBLISHERS_FAIL = "GET_PUBLISHERS_FAIL";

export const GET_PUBLISHER_DETAILS_START = "GET_PUBLISHER_DETAILS_START";
export const GET_PUBLISHER_DETAILS_SUCCESS = "GET_PUBLISHER_DETAILS_SUCCESS";
export const GET_PUBLISHER_DETAILS_FAIL = "GET_PUBLISHER_DETAILS_FAIL";

export const PUT_PUBLISHER_START = "PUT_PUBLISHER_START";
export const PUT_PUBLISHER_SUCCESS = "PUT_PUBLISHER_SUCCESS";
export const PUT_PUBLISHER_FAIL = "PUT_PUBLISHER_FAIL";

export const DELETE_PUBLISHER_START = "DELETE_PUBLISHER_START";
export const DELETE_PUBLISHER_SUCCESS = "DELETE_PUBLISHER_SUCCESS";
export const DELETE_PUBLISHER_FAIL = "DELETE_PUBLISHER_FAIL";

export const CREATE_PUBLISHER_START = "CREATE_PUBLISHER_START";
export const CREATE_PUBLISHER_SUCCESS = "CREATE_PUBLISHER_SUCCESS";
export const CREATE_PUBLISHER_FAIL = "CREATE_PUBLISHER_FAIL";

// AUTHORS
export const GET_AUTHORS_START = "GET_AUTHORS_START";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FAIL = "GET_AUTHORS_FAIL";

export const GET_AUTHOR_DETAILS_START = "GET_AUTHOR_DETAILS_START";
export const GET_AUTHOR_DETAILS_SUCCESS = "GET_AUTHOR_DETAILS_SUCCESS";
export const GET_AUTHOR_DETAILS_FAIL = "GET_AUTHOR_DETAILS_FAIL";

export const PUT_AUTHOR_START = "PUT_AUTHOR_START";
export const PUT_AUTHOR_SUCCESS = "PUT_AUTHOR_SUCCESS";
export const PUT_AUTHOR_FAIL = "PUT_AUTHOR_FAIL";

export const DELETE_AUTHOR_START = "DELETE_AUTHOR_START";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_FAIL = "DELETE_AUTHOR_FAIL";

export const CREATE_AUTHOR_START = "CREATE_AUTHOR_START";
export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
export const CREATE_AUTHOR_FAIL = "CREATE_AUTHOR_FAIL";

//AUTHENTICATION
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_REGISTRATIONS_START = "GET_REGISTRATIONS_START";
export const GET_REGISTRATIONS_SUCCESS = "GET_REGISTRATIONS_SUCCESS";
export const GET_REGISTRATIONS_FAIL = "GET_REGISTRATIONS_FAIL";

//USERS
export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

//LOANS
export const GET_LOANS_START = "GET_LOANS_START";
export const GET_LOANS_SUCCESS = "GET_LOANS_SUCCESS";
export const GET_LOANS_FAIL = "GET_LOANS_FAIL";

export const PUT_LOAN_START = "PUT_LOAN_START";
export const PUT_LOAN_SUCCESS = "PUT_LOAN_SUCCESS";
export const PUT_LOAN_FAIL = "PUT_LOAN_FAIL";

export const DELETE_LOAN_START = "DELETE_LOAN_START";
export const DELETE_LOAN_SUCCESS = "DELETE_LOAN_SUCCESS";
export const DELETE_LOAN_FAIL = "DELETE_LOAN_FAIL";

export const CREATE_LOAN_START = "CREATE_LOAN_START";
export const CREATE_LOAN_SUCCESS = "CREATE_LOAN_SUCCESS";
export const CREATE_LOAN_FAIL = "CREATE_LOAN_FAIL";

//COMMENTS
export const GET_BOOK_COMMENTS_START = "GET_BOOK_COMMENTS_START";
export const GET_BOOK_COMMENTS_SUCCESS = "GET_BOOK_COMMENTS_SUCCESS";
export const GET_BOOK_COMMENTS_FAIL = "GET_BOOK_COMMENTS_FAIL";

export const CREATE_BOOK_COMMENT_START = "CREATE_BOOK_COMMENT_START";
export const CREATE_BOOK_COMMENT_SUCCESS = "CREATE_BOOK_COMMENT_SUCCESS";
export const CREATE_BOOK_COMMENT_FAIL = "CREATE_BOOK_COMMENT_FAIL";

